(() => {
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const stateMarkup=s=>{const labels={goal:'任务目标',currentRequest:'当前请求',constraints:'约束',decisions:'已确定事项',plan:'计划',pending:'待办',summary:'进度摘要'};return `<section class="context-state"><h3>任务状态 <small>${esc(({running:'执行中',completed:'已完成',failed:'未完成',cancelled:'已停止'})[s.status]||'等待任务')}</small></h3><dl>${Object.entries(labels).filter(([key])=>s[key]).map(([key,label])=>`<dt>${label}</dt><dd>${esc(s[key])}</dd>`).join('')}</dl></section>`;};
 const api=(url,method='GET',body)=>window.DongranRuntime.request(url,method,body);
 const dialog=document.createElement('dialog');dialog.className='tools-window context-window';dialog.id='context-window';document.body.append(dialog);
 const close=()=>{dialog.classList.add('is-leaving');setTimeout(()=>dialog.close(),120);};dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 async function inspect(task){try{const data=await api('/api/tasks/'+task+'/context');dialog.classList.remove('is-leaving');dialog.innerHTML=`<header class="tools-heading"><div><h2>本轮上下文</h2><p>查看实际加载的记忆、预算与工具记录</p></div><button class="icon-btn" data-context-close aria-label="关闭上下文">×</button></header><div class="context-body">${stateMarkup(data.state)}${data.rounds.map(round=>{const r=JSON.parse(round.document);return `<section class="context-round"><h3>${round.role==='lead'?'主 Agent':esc(round.role)} · 第 ${r.turn+1} 次调用 <small>${esc(new Date(round.created_at).toLocaleTimeString())}</small></h3><div class="context-metrics"><span>输入 ≈ ${r.inputEstimated}</span><span>工具 ≈ ${r.toolEstimated}</span><span>输出预留 ${r.outputReserve}</span><span>容量 ${r.contextWindow}</span></div><progress max="${r.contextWindow}" value="${r.inputEstimated+r.toolEstimated+r.outputReserve}"></progress><small>Token 为估算值 · ${r.status==='ready'?'预算正常':'超过预算'}</small><p>${r.compactedMessages?`已压缩 ${r.compactedMessages} 条历史；原始记录保留。`:'未裁剪历史。'}</p><h4>使用的技能</h4>${(r.skills||[]).map(s=>`<div class="context-memory"><strong>${esc(s.name)}</strong><small>v${esc(s.version)} · ${esc(s.reason)} · 正文约 ${s.estimated_tokens} tokens</small></div>`).join('')||'<p class="context-muted">本次没有加载技能。</p>'}<h4>使用的记忆</h4>${r.memories.map(m=>`<div class="context-memory"><strong>${esc(m.title)}</strong><small>${m.scope==='global'?'全局':'项目'} · v${m.version}</small><p>${esc(m.content)}</p></div>`).join('')||'<p class="context-muted">本次没有匹配记忆。</p>'}<h4>可追溯证据</h4>${r.evidence.map(e=>`<button class="secondary" data-evidence="${esc(e.id)}">${esc(e.kind)} · ${e.length} 字符</button>`).join('')}${r.summaryEvidenceId?`<button class="secondary" data-evidence="${esc(r.summaryEvidenceId)}">压缩前历史原文</button>`:''}</section>`;}).join('')||'<p>尚未生成上下文快照。</p>'}<details><summary>工具执行记录</summary><pre>${esc(JSON.stringify(data.executions,null,2))}</pre></details><section id="context-evidence-view" hidden><h3>原始证据</h3><pre></pre><button class="secondary">继续读取</button></section></div>`;dialog.querySelector('[data-context-close]').onclick=close;let evidenceId='',offset=0;async function read(){const data=await api(`/api/tasks/${task}/evidence/${evidenceId}?offset=${offset}`);const host=dialog.querySelector('#context-evidence-view');host.hidden=false;host.querySelector('pre').textContent=(offset?host.querySelector('pre').textContent:'')+data.content;offset=data.nextOffset;host.querySelector('button').disabled=offset>=data.total;host.scrollIntoView({behavior:'smooth',block:'nearest'});}dialog.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>{evidenceId=b.dataset.evidence;offset=0;read().catch(e=>toast(e.message));});dialog.querySelector('#context-evidence-view button').onclick=()=>read().catch(e=>toast(e.message));if(!dialog.open)dialog.showModal();}catch(error){toast(error.message);}}
 let loading=false;
 async function refreshMemories(){const host=document.querySelector('#memory-intelligence');if(!host||loading||!window.DongranRuntime?.enabled)return;loading=true;try{const rows=await api('/api/memory-records');if(!host.isConnected)return;const project=window.DongranMemory?.getProject();const visible=rows.filter(r=>r.project_id==null||r.project_id===project?.id);const labels={candidate:'待审阅',active:'使用中',archived:'已归档',rejected:'已拒绝',deleted:'已删除'};host.innerHTML=`<h2>自动提炼与记忆版本</h2><p class="context-muted">只从用户原话提炼稳定偏好与约定；自动结果先进入候选，接受后才参与回答。固定记忆优先加载，其余按相关性选择。资料保存在本机，被选中时会发送给当前模型服务。</p><button class="settings-command" id="memory-refresh">刷新候选</button>${visible.map(r=>`<article class="context-memory"><strong>${esc(r.title)}</strong><small>${esc(labels[r.status])} · ${r.project_id?'当前项目':'全局'} · v${r.version}${r.pinned?' · 固定':''}</small><p>${esc(r.content)}</p>${r.source_quote?`<details><summary>提炼来源 · ${esc(r.origin)}</summary><blockquote>${esc(r.source_quote)}</blockquote><small>任务 ${esc(r.source_task)} · 消息 ${r.source_message}</small></details>`:''}<div class="runtime-actions">${r.status==='candidate'?`<button class="primary" data-memory-state="active" data-id="${esc(r.id)}" data-version="${r.version}">接受</button><button class="secondary" data-memory-state="rejected" data-id="${esc(r.id)}" data-version="${r.version}">拒绝</button>`:''}${r.status==='active'?`<button class="secondary" data-pin="${esc(r.id)}" data-pinned="${!r.pinned}">${r.pinned?'取消固定':'固定约定'}</button><button class="secondary" data-memory-state="archived" data-id="${esc(r.id)}" data-version="${r.version}">归档 / 撤销使用</button>`:''}${['archived','rejected','deleted'].includes(r.status)?`<button class="secondary" data-memory-state="active" data-id="${esc(r.id)}" data-version="${r.version}">恢复使用</button>`:''}<button class="secondary" data-history="${esc(r.id)}">版本记录</button></div><pre class="memory-version-view" hidden></pre></article>`).join('')||'<p>暂无候选或记忆记录。</p>'}`;
 host.querySelector('#memory-refresh').onclick=refreshMemories;
 host.querySelectorAll('[data-memory-state]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('/api/memory-records/'+b.dataset.id+'/status','POST',{status:b.dataset.memoryState,version:Number(b.dataset.version)});await sync();}catch(e){toast(e.message);}finally{b.disabled=false;}});
 host.querySelectorAll('[data-pin]').forEach(b=>b.onclick=async()=>{try{await api('/api/memory-records/'+b.dataset.pin+'/pin','POST',{pinned:b.dataset.pinned==='true'});await sync();}catch(e){toast(e.message);}});
 host.querySelectorAll('[data-history]').forEach(b=>b.onclick=async()=>{try{const rows=await api('/api/memory-records/'+b.dataset.history+'/history');const pre=b.closest('article').querySelector('pre');pre.hidden=false;pre.textContent=rows.length?rows.map(r=>JSON.stringify(JSON.parse(r.document),null,2)).join('\n\n'):'暂无历史版本。';}catch(e){toast(e.message);}});
 }catch(e){host.textContent=e.message;}finally{loading=false;}}
 async function sync(){const values=await api('/api/settings');window.DongranSettings.hydrate(values);await refreshMemories();}
 document.addEventListener('click',e=>{const button=e.target.closest('[data-context-task]');if(button)inspect(button.dataset.contextTask);});
 (window.DongranSettingsModules||=[]).push({categories:[{id:'context',label:'上下文工程',icon:'layers',group:'Agent 与项目',subtitle:'管理上下文预算、历史压缩与安全重试。'}],definitions:[
 {key:'contextAutoCompact',category:'context',section:'上下文预算',title:'自动压缩旧历史',description:'超出预算时归档较早历史，保留任务状态、近期请求和完整工具调用。',icon:'archive',type:'toggle',default:true},
 {key:'contextOutputReserve',category:'context',section:'上下文预算',title:'输出预留',description:'实际最多使用模型上下文的三分之一；服务商还可能有更低的输出上限。',icon:'text',type:'number',default:4096,min:512,max:16384,step:1},
 {key:'contextRetryLimit',category:'context',section:'恢复策略',title:'截断重试次数',description:'参数不完整时不执行；要求模型重新生成较小的完整调用。',icon:'rotate-cw',type:'number',default:1,min:0,max:3,step:1},
 {key:'contextMemoryLimit',category:'context',section:'记忆召回',title:'每轮记忆条数上限',description:'固定约定优先，其余按问题相关性选择，仍受 token 预算限制。',icon:'brain',type:'number',default:8,min:1,max:20,step:1}
 ],render(category){if(category==='memory'){setTimeout(refreshMemories,0);return '<section id="memory-intelligence" class="settings-section">正在读取记忆候选…</section>';}return '';}});
 window.DongranContext={inspect,refreshMemories};
})();
