(() => {
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const api=(path,method='GET',body)=>DongranRuntime.request('/api/skills'+path,method,body);
 const project=()=>window.DongranMemory?.getProject()?.id||null;
 const query=()=>project()?'?projectId='+encodeURIComponent(project()):'';
 const glyph=name=>`<i data-lucide="${name}"></i>`;
 const icons=()=>window.lucide?.createIcons();
 let selected=[],catalog=[],auto=true,scope=null,pickerIndex=0,pickerRows=[];
 const modal=document.createElement('dialog');modal.id='skill-editor';modal.className='tools-window skill-editor';document.body.append(modal);
 // This dialog has its own lifecycle; shared menus may be hosted inside it.
 const closeModal=()=>{DongranUI.closeMenu({immediate:true,restoreFocus:false});modal.close();};
 modal.addEventListener('cancel',e=>{e.preventDefault();closeModal();});
 function open(title,body){modal.innerHTML=`<header class="tools-heading"><div><h2>${esc(title)}</h2><p>技能定义工作方法，执行仍遵守工具权限。</p></div><button type="button" class="icon-btn" data-skill-close aria-label="关闭技能窗口">×</button></header><div class="skill-dialog-body">${body}</div>`;modal.querySelector('[data-skill-close]').onclick=closeModal;if(!modal.open)modal.showModal();icons();}
 const status=(text,bad=false)=>{const n=modal.querySelector('[data-skill-notice]');if(n){n.textContent=text;n.classList.toggle('is-error',bad);}else toast(text);};
 async function list(){catalog=await api(query());return catalog;}
 async function refresh(){const host=document.querySelector('#skill-manager');if(!host)return;try{await list();if(!host.isConnected)return;host.innerHTML=`<div class="skill-toolbar"><span>已安装 ${catalog.length} 个技能</span><button class="settings-command" data-new>新建技能</button><button class="settings-command" data-import>导入技能</button>${project()?'<button class="settings-command" data-scan>扫描项目目录</button>':''}<button class="settings-command" data-refresh>刷新</button></div><p class="skill-hint">全局技能跨项目使用；项目同名技能覆盖全局。关闭自动匹配后，仍可在聊天中主动选择。</p><div class="skill-grid">${catalog.map(r=>`<article class="skill-card ${!r.effective?'is-shadowed':''}"><div class="skill-card-heading">${glyph('book-open')}<strong>${esc(r.name)}</strong><span>v${esc(r.version)}</span></div><p>${esc(r.description)}</p><small>${r.project_id?'当前项目':'全局'} · ${esc(({builtin:'内置',zip:'ZIP 导入',directory:'目录导入',manual:'手动创建',project:'项目目录'})[r.source]||r.source)}${!r.effective?' · 被项目同名技能覆盖':''}</small><div class="skill-toggles"><label><input type="checkbox" data-enabled="${esc(r.id)}" ${r.enabled?'checked':''}>启用</label><label><input type="checkbox" data-auto="${esc(r.id)}" ${r.auto_match?'checked':''}>自动匹配</label></div><div class="skill-card-actions"><button class="settings-command" data-edit="${esc(r.id)}">查看 / 编辑</button><button class="settings-command" data-delete="${esc(r.id)}">卸载</button></div></article>`).join('')||'<p class="skill-hint">还没有技能，导入包含 SKILL.md 的目录或 ZIP 开始使用。</p>'}</div>`;
 host.querySelector('[data-new]').onclick=()=>editor();host.querySelector('[data-import]').onclick=importer;host.querySelector('[data-refresh]').onclick=refresh;host.querySelector('[data-scan]')?.addEventListener('click',async()=>{try{await api('/scan','POST',{projectId:project()});await refresh();toast('已扫描 .dongran/skills，已有条目保留启停状态。');}catch(e){toast(e.message);}});
 host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editor(b.dataset.edit));host.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete));
 host.querySelectorAll('[data-enabled],[data-auto]').forEach(input=>input.onchange=async()=>{const row=catalog.find(r=>r.id===(input.dataset.enabled||input.dataset.auto));try{await api('/'+row.id+'/state','POST',{enabled:input.dataset.enabled?input.checked:!!row.enabled,autoMatch:input.dataset.auto?input.checked:!!row.auto_match});await refresh();}catch(e){toast(e.message);input.checked=!input.checked;}});
 icons();}catch(e){host.textContent=e.message;}}
 function scopePicker(){const b=modal.querySelector('[data-scope]');if(!b)return;b.textContent=scope?'当前项目':'全局';b.onclick=()=>DongranUI.showMenu(b,{label:'安装范围',items:[{value:'global',label:'全局'},...(project()?[{value:'project',label:'当前项目'}]:[])],onSelect:v=>{scope=v==='project'?project():null;scopePicker();}});}
 const sample='---\nname: my-skill\ndescription: 描述适用场景，例如编写需求文档、代码审查\nversion: 1.0.0\n---\n\n# 执行步骤\n\n1. 明确用户目标和范围。\n2. 阅读实际资料，调用所需工具。\n3. 输出结果与未验证事项。\n';
 async function editor(id){try{const row=id?await api('/'+id):null;scope=row?.project_id||project();open(row?'编辑技能':'新建技能',`<form id="skill-form"><div class="skill-toolbar"><span>范围</span>${row?`<span>${row.project_id?'当前项目':'全局'}</span>`:'<button class="settings-command" type="button" data-scope></button>'}${row?`<small>版本 ${esc(row.version)} · ${esc(row.content_hash.slice(0,12))}</small>`:''}</div>${row?.changed?'<p class="is-error">磁盘内容已变更。保存将审阅并同步当前内容，之后才允许 Agent 使用。</p>':''}<label class="skill-field">SKILL.md<textarea id="skill-content" spellcheck="false" rows="16">${esc(row?.content??sample)}</textarea></label><p class="skill-hint">YAML 元数据包含 name、description、version。参考文件放入 references/，模板放入 templates/，脚本放入 scripts/。</p>${row?`<details><summary>包内资源（${row.files.length}）</summary><ul>${row.files.map(f=>`<li>${esc(f)}</li>`).join('')}</ul><p>${esc(row.root_path)}</p></details>`:''}<p data-skill-notice role="status"></p><div class="skill-card-actions"><button type="submit" class="primary">保存技能</button></div></form>`);scopePicker();modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const content=modal.querySelector('textarea').value;await api(id?'/'+id:'',id?'PUT':'POST',{content,projectId:scope,expectedHash:row?.diskHash});closeModal();await refresh();toast('技能已保存');}catch(err){status(err.message,true);}finally{b.disabled=false;}};}catch(e){toast(e.message);}}
 function importer(){scope=project();open('导入技能',`<div class="skill-toolbar"><span>安装范围</span><button type="button" class="settings-command" data-scope></button></div><form id="skill-directory-form"><label class="skill-field">技能目录路径<input id="skill-directory" placeholder="包含 SKILL.md 的文件夹绝对路径" autocomplete="off" required></label><button class="primary" type="submit">导入目录</button></form><div class="skill-import-divider">或选择技能压缩包</div><label class="settings-command skill-upload">${glyph('upload')}导入 ZIP<input type="file" id="skill-zip" accept=".zip" hidden></label><p class="skill-hint">导入时复制到应用管理目录；最多 200 个文件，解压后总大小 2MB。不允许链接或越界路径。</p><p data-skill-notice role="status"></p>`);scopePicker();modal.querySelector('form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await api('/directory','POST',{path:modal.querySelector('#skill-directory').value,projectId:scope});closeModal();await refresh();}catch(err){status(err.message,true);}finally{e.submitter.disabled=false;}};modal.querySelector('#skill-zip').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const body=new FormData();body.append('file',file);await DongranBackend.request('/api/skills/zip'+(scope?'?projectId='+encodeURIComponent(scope):''),{method:'POST',body});closeModal();await refresh();}catch(err){status(err.message,true);}finally{e.target.value='';}};}
 function remove(id){const row=catalog.find(r=>r.id===id);open('卸载技能',`<p>卸载 ${esc(row.name)} 会删除应用管理的技能包目录。原始导入目录和项目产物保留。</p><p data-skill-notice role="status"></p><button class="primary" data-confirm-delete>卸载技能</button>`);modal.querySelector('[data-confirm-delete]').onclick=async e=>{e.target.disabled=true;try{await api('/'+id,'DELETE');selected=selected.filter(r=>r.id!==id);chips();closeModal();await refresh();}catch(err){status(err.message,true);e.target.disabled=false;}};}
 const composer=document.querySelector('#composer');const prompt=document.querySelector('#prompt');
 const bar=document.createElement('div');bar.className='skill-composer-bar';bar.innerHTML=`<div class="skill-controls"><button type="button" id="skill-picker-button" aria-haspopup="dialog" aria-expanded="false">${glyph('book-open')}<span>技能</span><kbd>/</kbd>${glyph('chevron-down')}</button><label class="skill-auto-control" title="根据本轮任务自动选择相关技能"><input id="skill-auto-toggle" type="checkbox" checked role="switch"><span class="skill-switch-track" aria-hidden="true"></span><span>自动匹配</span></label></div><div id="skill-selected"></div>`;composer.prepend(bar);
 const trigger=bar.querySelector('#skill-picker-button');
 const picker=document.createElement('div');picker.id='skill-picker';picker.className='skill-picker';picker.hidden=true;picker.setAttribute('role','dialog');picker.setAttribute('aria-label','选择技能');document.body.append(picker);
 let requestVersion=0,queryText='',pickerLoading=false;
 function placePicker(){if(picker.hidden)return;const r=trigger.getBoundingClientRect(),height=picker.offsetHeight,width=picker.offsetWidth;picker.style.left=Math.max(12,Math.min(r.left,innerWidth-width-12))+'px';picker.style.top=Math.max(12,r.top-height-8)+'px';}
 const hide=()=>{requestVersion++;picker.hidden=true;prompt.removeAttribute('aria-activedescendant');trigger.setAttribute('aria-expanded','false');};
 function chips(){document.querySelector('#skill-selected').innerHTML=selected.map(r=>`<button type="button" data-skill-remove="${esc(r.id)}" aria-label="移除技能 ${esc(r.name)}">${esc(r.name)} <span>×</span></button>`).join('');bar.querySelectorAll('[data-skill-remove]').forEach(b=>b.onclick=()=>{selected=selected.filter(r=>r.id!==b.dataset.skillRemove);chips();});}
 async function choose(row){if(pickerLoading)return;if(selected.length>=3&&!selected.some(r=>r.id===row.id)){toast('每轮最多选择 3 个技能');return;}pickerLoading=true;try{if(!row.enabled){await api('/'+row.id+'/state','POST',{enabled:true,autoMatch:!!row.auto_match});row.enabled=1;}if(!selected.some(r=>r.id===row.id))selected.push(row);if(/^\/[^\n]*$/.test(prompt.value))prompt.value='';chips();hide();prompt.focus();}catch(e){toast(e.message);}finally{pickerLoading=false;}}
 function paintPicker(filter=''){queryText=filter;pickerRows=catalog.filter(r=>r.effective&&(r.name+' '+r.description).toLowerCase().includes(filter.toLowerCase()));pickerIndex=Math.min(pickerIndex,Math.max(0,pickerRows.length-1));picker.querySelector('.skill-picker-options').innerHTML=pickerRows.map((r,i)=>`<button type="button" role="option" aria-selected="${i===pickerIndex}" id="skill-option-${i}" data-index="${i}" class="${r.enabled?'':'is-disabled-skill'}"><span class="skill-option-title"><strong>${esc(r.name)}</strong><small>${selected.some(s=>s.id===r.id)?'已选择':r.enabled?(r.project_id?'项目':'全局'):'启用并选择'}</small></span><small>${esc(r.description)}</small></button>`).join('')||'<p>没有匹配的技能。可到设置中创建或导入。</p>';picker.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>choose(pickerRows[Number(b.dataset.index)]));const owner=picker.querySelector('input');if(pickerRows.length){owner.setAttribute('aria-activedescendant','skill-option-'+pickerIndex);prompt.setAttribute('aria-activedescendant','skill-option-'+pickerIndex);}else{owner.removeAttribute('aria-activedescendant');prompt.removeAttribute('aria-activedescendant');}picker.querySelector('[aria-selected="true"]')?.scrollIntoView({block:'nearest'});placePicker();}
 async function showPicker(fromButton=false){const version=++requestVersion;pickerIndex=0;picker.innerHTML=`<div class="skill-picker-heading"><strong>选择技能</strong><span>最多 3 个</span></div><label class="skill-picker-search">${glyph('search')}<input aria-label="搜索技能" role="combobox" aria-autocomplete="list" aria-controls="skill-options" aria-expanded="true" placeholder="搜索技能名称或用途…"></label><div class="skill-picker-options" id="skill-options" role="listbox"><p>正在读取技能…</p></div><div class="skill-picker-footer"><span>↑ ↓ 选择 · Enter 确定</span><button type="button" data-manage-skills>管理技能 ${glyph('arrow-up-right')}</button></div>`;picker.hidden=false;trigger.setAttribute('aria-expanded','true');const search=picker.querySelector('input');search.value=fromButton?'':prompt.value.startsWith('/')?prompt.value.slice(1):'';queryText=search.value;search.oninput=()=>{pickerIndex=0;paintPicker(search.value);};search.addEventListener('keydown',pickerKey);picker.querySelector('[data-manage-skills]').onclick=()=>{hide();DongranSettings.open('skills');};icons();placePicker();if(fromButton)search.focus();try{await list();if(version!==requestVersion)return;paintPicker(queryText);}catch(e){if(version===requestVersion){picker.querySelector('.skill-picker-options').innerHTML='<p>'+esc(e.message)+'</p>';placePicker();}}}
 function pickerKey(e){if(e.isComposing||picker.hidden)return;if(['Enter','ArrowDown','ArrowUp','Escape'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();if(e.key==='Escape'){hide();prompt.focus();}else if(e.key==='Enter'){if(pickerRows[pickerIndex])choose(pickerRows[pickerIndex]);}else{pickerIndex=(pickerIndex+(e.key==='ArrowDown'?1:-1)+Math.max(1,pickerRows.length))%Math.max(1,pickerRows.length);paintPicker(queryText);}}}
 trigger.onclick=()=>picker.hidden?showPicker(true):hide();document.querySelector('#skill-auto-toggle').onchange=e=>auto=e.target.checked;
 prompt.addEventListener('input',()=>{if(/^\/[^\n]*$/.test(prompt.value))showPicker();else hide();});
 prompt.addEventListener('keydown',e=>{if(e.isComposing)return;if(picker.hidden){if(e.key==='Enter'&&/^\/[^\n]*$/.test(prompt.value)){e.preventDefault();e.stopImmediatePropagation();showPicker();}return;}pickerKey(e);},true);
 document.addEventListener('pointerdown',e=>{if(!picker.contains(e.target)&&!bar.contains(e.target)&&e.target!==prompt)hide();});
 window.addEventListener('resize',placePicker);document.addEventListener('scroll',e=>{if(!picker.contains(e.target))placePicker();},true);
 function reset(){selected=[];auto=true;document.querySelector('#skill-auto-toggle').checked=true;hide();chips();}
 window.addEventListener('projectchange',reset);
 document.addEventListener('click',e=>{if(e.target.closest('[data-open-skills]'))DongranSettings.open('skills');if(e.target.closest('[data-action="new"]'))reset();});
 (window.DongranSettingsModules||=[]).push({categories:[{id:'skills',label:'技能',icon:'book-open',group:'Agent 与项目',subtitle:'管理可复用的工作流程、规范与模板。',searchKeywords:'skill 技能 导入 SKILL.md'}],definitions:[],render(category){if(category!=='skills')return '';setTimeout(refresh,0);return '<section id="skill-manager" class="settings-section">正在读取技能…</section>';}});
 async function evolution(){
   const host=document.querySelector('#skill-manager'); if(!host)return;
   try{
     const listed=await DongranRuntime.request('/api/skill-evolution/candidates'+query());
     const rows=await Promise.all(listed.map(r=>DongranRuntime.request('/api/skill-evolution/candidates/'+encodeURIComponent(r.id)).then(d=>({...r,...d}))));
     // The candidate history spans projects in global view; show its published skills too,
     // without adding out-of-scope skills to the chat picker catalog.
     const published=await Promise.all([...new Set(rows.filter(r=>r.status==='approved'&&r.skill_id&&!catalog.some(s=>s.id===r.skill_id)).map(r=>r.skill_id))].map(id=>api('/'+encodeURIComponent(id)).catch(()=>null)));
     for(const skill of published.filter(Boolean)){
       const card=document.createElement('article');card.className='skill-card';
       card.innerHTML=`<div class="skill-card-heading"><strong>${esc(skill.name)}</strong><span>v${esc(skill.version)}</span></div><p>${esc(skill.description)}</p><small>其他项目 · 已发布的演进技能 · ${skill.enabled?'已启用':'未启用'}</small><div class="skill-card-actions"><button class="settings-command" data-published-edit>查看 / 编辑</button></div>`;
       card.querySelector('button').onclick=()=>editor(skill.id);host.querySelector('.skill-grid')?.append(card);
     }
     const runs=await DongranRuntime.request('/api/skill-evolution/runs'+query());
     const section=document.createElement('section'); section.className='skill-evolution-panel';
     section.innerHTML='<div class="skill-toolbar"><strong>待审核的技能改进候选</strong><span class="skill-hint">成功与失败任务都会生成候选，发布前需评测和人工审核。</span></div>'+rows.map(r=>`<article class="skill-candidate" data-candidate="${esc(r.id)}"><div><strong>${esc(r.name)}</strong><span> ${esc(r.status)}</span></div><p>${esc(r.description||'')}</p><details><summary>查看 Diff</summary><pre>${esc(r.content||'')}</pre></details><div class="skill-card-actions"><button class="settings-command" data-eval>评测</button><button class="primary" data-approve>批准发布</button><button class="settings-command" data-reject>拒绝</button></div></article>`).join('');
     if(!rows.length)section.insertAdjacentHTML('beforeend','<p class="skill-hint">暂无候选。完成任务后点击刷新，下面可查看提炼进度、跳过原因或失败记录。</p>');
     section.querySelectorAll('[data-candidate]').forEach(card=>{
       const row=rows.find(r=>r.id===card.dataset.candidate),latest=row.results?.[0];
       const report=document.createElement('div');report.className='skill-evaluation-report';
       report.innerHTML='<strong>评测结果</strong>'+ (row.results?.length?row.results.map(r=>{let p;try{p=JSON.parse(r.report);}catch{p={reason:r.report};}return `<details open><summary>${r.status==='passed'?'通过':'未通过'} · ${esc(r.created_at)}</summary><p>${esc(p.reason||'无评审理由')}</p><small>静态检查 + 模型模拟评审 · 未执行真实测试</small></details>`;}).join(''):'<p>尚未评测，批准前需通过模拟评审。</p>');
       card.querySelector('.skill-card-actions').before(report);
       const pending=row.status==='pending_review';
       card.querySelectorAll('button').forEach(b=>b.disabled=!pending);
       card.querySelector('[data-approve]').disabled=!pending||latest?.status!=='passed';
       if(row.status==='approved'){
         const note=document.createElement('p');note.className='skill-hint';
         note.textContent='已发布到'+(row.project_id?'原任务所属项目':'全局')+'技能列表。新技能默认关闭，可在列表手动启用。';card.append(note);
         const entry=document.createElement('button');entry.className='settings-command';entry.textContent='查看已发布技能';
         entry.onclick=()=>editor(row.skill_id);card.append(entry);
       }
     });
     section.insertAdjacentHTML('beforeend','<details open><summary>最近提炼记录</summary>'+ (runs.map(r=>`<article class="skill-candidate"><strong>${esc(r.title||r.task_id)}</strong><p>${esc(({queued:'排队中',running:'提炼中',completed:'已生成候选',skipped:'无可复用经验',failed:'生成失败',interrupted:'已中断'})[r.status]||r.status)} · ${esc(r.trigger==='success'?'成功任务':'失败任务')}</p><p>${esc(r.diagnosis||'')}</p></article>`).join('')||'<p class="skill-hint">尚无提炼记录；开启自动生成后，新结束的任务才会触发。</p>')+'</details>');
     host.prepend(section); section.querySelectorAll('[data-candidate]').forEach(card=>{const id=card.dataset.candidate;for(const [selector,action] of [['[data-eval]','evaluate'],['[data-approve]','approve'],['[data-reject]','reject']])card.querySelector(selector).onclick=async()=>{card.querySelectorAll('button').forEach(b=>b.disabled=true);try{await DongranRuntime.request('/api/skill-evolution/candidates/'+id+'/'+action,'POST');await refresh();toast(action==='evaluate'?'评测完成，结果已显示':action==='approve'?'已发布，请在技能列表查看':'已拒绝');}catch(e){await refresh();toast(e.message);}};});
   }catch(e){const notice=document.createElement('p');notice.className='runtime-error';notice.textContent='技能演进读取失败：'+e.message;host.prepend(notice);}
 }
 const originalRefresh=refresh; refresh=async()=>{await originalRefresh();await evolution();};
 window.DongranSkills={refresh,reset,payload:()=>({skillIds:selected.map(r=>r.id),autoSkills:auto})};icons();
})();
