(() => {
  const dock=document.querySelector('#terminal-dock'),toggle=document.querySelector('#terminal-toggle');if(!dock||!toggle)return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icon=name=>`<i data-lucide="${name}"></i>`,icons=()=>window.lucide?.createIcons();
  const api=(url,method='GET',body)=>window.DongranBackend.request(url,{method,...(body===undefined?{}:{body:JSON.stringify(body)})});
  let project=null,active=null,split=null,mode='sandbox',profiles=[],creating=false,polling=false,restored=false,resizeFrame=0;
  const sessions=new Map();
  dock.innerHTML=`<div class="terminal-resizer" role="separator" tabindex="0" aria-label="调整终端高度" aria-orientation="horizontal"></div>
    <header class="terminal-heading"><div class="terminal-tab">${icon('terminal')}<strong>终端</strong><span class="terminal-demo">工作区</span></div><span id="terminal-project" class="terminal-project">未选择项目</span><div class="terminal-actions">
      <button class="terminal-mode" id="terminal-mode" type="button" aria-haspopup="menu" title="新建另一种模式的会话">${icon('shield')}<span>沙箱</span>${icon('chevron-down')}</button>
      <div class="terminal-new-group"><button class="icon-btn" id="terminal-new" title="新建终端" aria-label="新建终端">${icon('plus')}</button><button class="icon-btn" id="terminal-profiles" title="选择 Shell" aria-label="选择 Shell" aria-haspopup="menu">${icon('chevron-down')}</button></div>
      <button class="icon-btn" id="terminal-split" title="分屏终端" aria-label="分屏终端">${icon('columns-2')}</button><button class="icon-btn" id="terminal-search" title="搜索输出 · Ctrl+Shift+F" aria-label="搜索终端">${icon('search')}</button><button class="icon-btn" id="terminal-more" title="更多操作" aria-label="终端更多操作" aria-haspopup="menu">${icon('ellipsis')}</button><button class="icon-btn" id="terminal-stop" title="终止当前会话" aria-label="终止当前会话">${icon('trash-2')}</button><button class="icon-btn" id="terminal-expand" title="最大化面板" aria-label="最大化终端" aria-pressed="false">${icon('maximize-2')}</button><button class="icon-btn" id="terminal-close" title="隐藏面板（保留会话）" aria-label="隐藏终端">${icon('x')}</button></div></header>
    <nav class="terminal-tabs" id="terminal-tabs" aria-label="终端会话"></nav>
    <div class="terminal-content"><div id="terminal-panes" class="terminal-panes"></div><div id="terminal-divider" class="terminal-divider" role="separator" aria-label="调整分屏宽度" aria-orientation="vertical" tabindex="0" hidden></div><div class="terminal-empty" id="terminal-empty">${icon('square-terminal')}<strong>让工作从这里开始</strong><p>本机终端支持持续会话与交互；沙箱命令在隔离的项目快照中运行。</p><div><button id="terminal-empty-host" class="primary">新建本机终端</button><button id="terminal-empty-sandbox" class="secondary">新建沙箱命令</button></div><small>本机终端使用你的系统权限，不改变 Agent 的沙箱策略。</small></div>
    <form id="terminal-find" class="terminal-find" hidden><input id="terminal-find-input" aria-label="搜索终端输出" placeholder="在终端中查找"><span id="terminal-find-state"></span><button type="button" data-find="previous" aria-label="上一个匹配">${icon('arrow-up')}</button><button type="submit" aria-label="下一个匹配">${icon('arrow-down')}</button><button type="button" data-find="close" aria-label="关闭查找">${icon('x')}</button></form></div>
    <form id="terminal-form" class="terminal-form" hidden><span class="terminal-prompt">❯</span><input id="terminal-input" aria-label="沙箱命令" placeholder="输入沙箱命令，Enter 执行" autocomplete="off" spellcheck="false"><button id="terminal-cancel-command" type="button" title="停止命令" hidden>${icon('square')}</button><button type="submit" title="执行命令">${icon('corner-down-left')}</button></form>
    <footer class="terminal-statusbar"><span id="terminal-shell">未启动</span><span id="terminal-status">选择项目后新建终端</span><span class="terminal-status-spacer"></span><button id="terminal-sandbox" type="button" title="查看沙箱设置">${icon('shield-check')}<span>权限设置</span></button><span id="terminal-size"></span></footer>`;
  const $=s=>dock.querySelector(s),current=()=>sessions.get(active),notice=message=>window.toast?.(message);
  function theme(){const dark=document.documentElement.dataset.theme==='dark';return {background:dark?'#191919':'#ffffff',foreground:dark?'#dedede':'#303030',cursor:dark?'#e4e4e4':'#343434',selectionBackground:dark?'#ffffff30':'#00000020',black:'#414141',red:'#c85a56',green:'#589568',yellow:'#b4944b',blue:'#538bc5',magenta:'#9d77b0',cyan:'#55a3aa',white:'#dedede',brightBlack:'#858585',brightWhite:'#ffffff'};}
  function update(){
    const s=current();if(s)mode=s.mode;
    $('#terminal-empty').hidden=sessions.size>0;$('#terminal-tabs').hidden=!sessions.size;
    $('#terminal-tabs').innerHTML=[...sessions.values()].map(s=>`<div class="terminal-session-tab ${s.id===active?'active':''}" data-session="${esc(s.id)}"><button class="terminal-session-select" title="${esc(s.directory)} · ${s.mode==='host'?'本机，非隔离':'沙箱'}" aria-pressed="${s.id===active}" data-select="${esc(s.id)}"><span class="terminal-state ${s.status==='exited'||s.status==='closed'?'exited':''}"></span>${icon(s.mode==='host'?'terminal':'shield')}<span>${esc(s.name)}</span><small>${s.mode==='host'?'本机':'沙箱'}</small></button><button data-close="${esc(s.id)}" class="terminal-tab-close" title="关闭会话" aria-label="关闭 ${esc(s.name)}">${icon('x')}</button></div>`).join('');
    dock.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>select(b.dataset.select));dock.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeSession(b.dataset.close));
    $('#terminal-panes').classList.toggle('is-split',!!split&&split!==active);$('#terminal-divider').hidden=!split||split===active;
    for(const item of sessions.values()){item.pane.hidden=item.id!==active&&item.id!==split;item.pane.classList.toggle('is-focused',item.id===active);}
    applySplit();
    $('#terminal-form').hidden=s?.mode!=='sandbox';$('#terminal-input').disabled=!s||s.running||window.DongranSandbox?.snapshot().available!==true;
    $('#terminal-cancel-command').hidden=!s?.running;
    $('#terminal-project').textContent=s?.directory||project?.path||'未选择项目';$('#terminal-project').title=s?.directory||project?.path||'';
    $('#terminal-mode').innerHTML=icon(mode==='host'?'monitor':'shield')+`<span>${mode==='host'?'本机 · 非隔离':'沙箱'}</span>`+icon('chevron-down');
    $('#terminal-shell').textContent=s?.name||'未启动';$('#terminal-status').textContent=!s?'选择模式以开始':s.mode==='host'?(s.status==='running'?'持久 Shell · 系统权限 · 关闭面板后继续运行':`会话已退出${s.exitCode==null?'':' · '+s.exitCode}`):(s.running?'命令执行中 · 网络关闭':window.DongranSandbox?.snapshot().available?'快照执行 · 成功后检查冲突并回写 · 网络关闭':'沙箱不可用 · '+(window.DongranSandbox?.snapshot().reason||'正在检测'));
    $('#terminal-size').textContent=s?`${s.term.cols} × ${s.term.rows}`:'';
    $('#terminal-new').title=mode==='host'?'新建本机终端':'新建沙箱命令';
    for(const id of ['terminal-split','terminal-search','terminal-more','terminal-stop'])$('#'+id).disabled=!s;
    $('#terminal-new').disabled=creating||!project;$('#terminal-empty-host').disabled=creating||!project;$('#terminal-empty-sandbox').disabled=creating||!project;
    icons();fitAll();
  }
  let splitRatio=50;
  function applySplit(){const visible=[...sessions.values()].filter(s=>!s.pane.hidden);visible.forEach((s,index)=>{s.pane.style.flex=visible.length===2?`0 0 ${index===0?splitRatio:100-splitRatio}%`:'1';});$('#terminal-divider').style.left=splitRatio+'%';}
  function select(id){if(!sessions.has(id))return;if(split===id)split=active;active=id;$('#terminal-find').hidden=true;update();setTimeout(()=>current()?.mode==='host'?current().term.focus():$('#terminal-input').focus(),0);}
  function fitAll(){cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(()=>{if(dock.hidden)return;for(const s of sessions.values()){if(s.pane.hidden)continue;try{s.fit.fit();const size=`${s.term.cols}:${s.term.rows}`;if(s.mode==='host'&&s.status==='running'&&size!==s.size){s.size=size;clearTimeout(s.resizeTimer);s.resizeTimer=setTimeout(()=>api(`/api/terminals/${s.id}/resize`,'POST',{cols:s.term.cols,rows:s.term.rows}).catch(()=>{}),100);}}catch{}}const s=current();if(s)$('#terminal-size').textContent=`${s.term.cols} × ${s.term.rows}`;});}
  new ResizeObserver(fitAll).observe(dock);
  function attach(row){
    const s={...row,cursor:0,input:'',sending:false,history:[],historyIndex:0,queue:Promise.resolve()};
    const pane=document.createElement('section');pane.className='terminal-pane';pane.setAttribute('aria-label',`${s.name} 终端`);pane.innerHTML=`<div class="terminal-pane-label"><span>${esc(s.name)}</span><small>${s.mode==='host'?'本机 · 非隔离':'沙箱'}</small></div><div class="terminal-canvas"></div>`;$('#terminal-panes').append(pane);s.pane=pane;
    s.term=new Terminal({cursorBlink:true,convertEol:false,scrollback:10000,fontFamily:'"Cascadia Code",Consolas,"Microsoft YaHei UI",monospace',fontSize:Number(window.DongranSettings?.get('terminalFontSize'))||13,lineHeight:1.08,theme:theme(),allowProposedApi:false,disableStdin:s.mode!=='host',rightClickSelectsWord:true});
    s.fit=new FitAddon.FitAddon();s.search=new SearchAddon.SearchAddon();s.term.loadAddon(s.fit);s.term.loadAddon(s.search);s.term.open(pane.querySelector('.terminal-canvas'));
    pane.addEventListener('pointerdown',()=>{if(active!==s.id){const previous=active;active=s.id;if(split===s.id)split=previous;update();}});
    s.term.onData(data=>send(s,data));s.term.onBinary(data=>send(s,data));
    s.term.attachCustomKeyEventHandler(event=>{if(event.type!=='keydown')return true;if(event.ctrlKey&&event.shiftKey&&['C','V','F'].includes(event.key.toUpperCase())){event.preventDefault();if(event.key.toUpperCase()==='C')copy(s);else if(event.key.toUpperCase()==='V')paste(s);else find();return false;}if(event.ctrlKey&&event.key==='c'&&s.term.hasSelection()){copy(s);return false;}return true;});
    pane.addEventListener('contextmenu',event=>{event.preventDefault();more(event.target.closest('.terminal-pane'),s);});
    sessions.set(s.id,s);return s;
  }
  function send(s,data){if(s.mode!=='host'||s.status!=='running')return;if(s.input.length+data.length>1048576){notice('输入队列已满，请等待终端处理。');return;}s.input+=data;if(s.sending)return;s.sending=true;setTimeout(async()=>{try{while(s.input&&sessions.has(s.id)){let end=Math.min(4096,s.input.length);if(end<s.input.length&&/[\uD800-\uDBFF]/.test(s.input[end-1]))end--;const chunk=s.input.slice(0,end);s.input=s.input.slice(end);await api(`/api/terminals/${s.id}/input`,'POST',{data:chunk});}}catch(error){s.input='';notice(error.message);}finally{s.sending=false;}},8);}
  async function loadProfiles(){profiles=await api('/api/terminals/profiles');return profiles;}
  function defaultProfile(){const chosen=window.DongranSettings?.get('shell');const ids={'PowerShell':'powershell','Command Prompt':'cmd','Git Bash':'git-bash'};return profiles.find(p=>p.id===ids[chosen])?.id||profiles[0]?.id;}
  async function create(kind=mode,profile,asSplit=false){if(creating)return null;if(!project){notice('请先选择项目目录。');return null;}if(sessions.size>=12){notice('最多保留 12 个终端，请关闭不用的会话。');return null;}creating=true;update();let s;
    try{if(kind==='host'){if(!profiles.length)await loadProfiles();const row=await api('/api/terminals','POST',{projectId:project.id,profile:profile||defaultProfile(),cols:100,rows:24,confirmed:true});s=attach({...row,mode:'host'});}else{await window.DongranSandbox?.refresh();const status=window.DongranSandbox?.snapshot();if(!status?.available)throw Error(status?.reason||'命令沙箱未就绪');s=attach({id:'sandbox-'+crypto.randomUUID(),projectId:project.id,directory:project.path,name:'沙箱命令',mode:'sandbox',status:'running'});s.term.writeln('\x1b[90m隔离命令 · 每条命令在独立快照执行，非持久 Shell。\x1b[0m\r\n');}
      if(asSplit)split=active;else split=null;active=s.id;mode=kind;setOpen(true);update();if(kind==='host')s.term.focus();else $('#terminal-input').focus();startPoll();return s;
    }catch(error){notice(error.message);return null;}finally{creating=false;update();}}
  async function startPoll(){if(polling)return;polling=true;try{while([...sessions.values()].some(s=>s.mode==='host'&&s.status==='running')){const cursors=Object.fromEntries([...sessions.values()].filter(s=>s.mode==='host'&&s.status==='running').map(s=>[s.id,s.cursor]));try{const rows=await api('/api/terminals/poll','POST',cursors);for(const row of rows){const s=sessions.get(row.id);if(!s)continue;if(row.truncated)s.term.write('\r\n\x1b[90m[较早输出已截断]\x1b[0m\r\n');if(row.data){await new Promise(resolve=>s.term.write(row.data,resolve));if(s.id===active&&!$('#terminal-find').hidden&&$('#terminal-find-input').value)search();}s.cursor=row.cursor;if(row.status!==s.status){s.status=row.status;s.exitCode=row.exitCode;s.term.writeln(`\r\n\x1b[90m[进程已退出${row.exitCode==null?'':' · '+row.exitCode}]\x1b[0m`);update();}}}catch(error){$('#terminal-status').textContent='输出连接中断，正在重连…';await new Promise(r=>setTimeout(r,1000));}await new Promise(r=>setTimeout(r,dock.hidden?700:120));}}finally{polling=false;}}
  async function restore(){if(restored)return;try{const rows=await api('/api/terminals');for(const row of rows)if(!sessions.has(row.id))attach({...row,mode:'host'});restored=true;if(!active&&rows.length)active=rows.at(-1).id;const saved=await api('/api/terminals/poll','POST',Object.fromEntries(rows.map(row=>[row.id,0])));for(const row of saved){const s=sessions.get(row.id);if(s){s.term.write(row.data||'');s.cursor=row.cursor;}}update();startPoll();}catch{}}
  async function closeSession(id){const s=sessions.get(id);if(!s)return;try{if(s.mode==='host')await api('/api/terminals/'+id,'DELETE');else if(s.running==='starting'){notice('命令正在创建，请稍后停止。');return;}else if(s.running)await api('/api/commands/'+s.running+'/cancel','POST');sessions.delete(id);clearTimeout(s.resizeTimer);s.term.dispose();s.pane.remove();if(split===id)split=null;if(active===id){active=split||[...sessions.keys()].at(-1)||null;split=null;}update();}catch(error){notice(error.message);}}
  async function sandboxCommand(command){const s=current();if(!s||s.mode!=='sandbox'||s.running||!command)return;if(window.DongranSandbox?.snapshot().available!==true){notice('命令沙箱未就绪。');return;}s.running='starting';s.history.push(command);s.historyIndex=s.history.length;s.term.writeln('\r\n\x1b[1m❯ '+command+'\x1b[0m');update();let previous='';try{const run=await api('/api/commands','POST',{projectId:s.projectId,command,confirmed:true,timeout:120});s.running=run.id;update();while(sessions.has(s.id)){const result=await api('/api/commands/'+run.id);const text=result.output||'';const delta=text.startsWith(previous)?text.slice(previous.length):text;s.term.write(delta.replace(/\r?\n/g,'\r\n'));previous=text;if(!['queued','running'].includes(result.status)){s.term.writeln(`\r\n\x1b[90m[${result.status} · exit ${result.exit_code??'—'} · ${result.syncStatus||'未回写'}]\x1b[0m`);break;}await new Promise(r=>setTimeout(r,250));}}catch(error){if(sessions.has(s.id))s.term.writeln('\r\n\x1b[31m'+error.message+'\x1b[0m');}finally{s.running=null;update();if(current()===s)$('#terminal-input').focus();}}
  async function copy(s=current()){if(!s)return;try{await navigator.clipboard.writeText(s.term.getSelection());}catch{notice('无法访问剪贴板，请使用系统复制快捷键。');}}
  async function paste(s=current()){if(!s)return;try{const text=await navigator.clipboard.readText();if(s.mode==='host')s.term.paste(text);else{$('#terminal-input').value=text;$('#terminal-input').focus();}}catch{notice('请在终端中使用 Ctrl+V 粘贴。');}}
  function find(){if(!current())return;$('#terminal-find').hidden=false;$('#terminal-find-input').focus();}
  function search(previous=false){const s=current(),text=$('#terminal-find-input').value;if(!s)return;const match=previous?s.search.findPrevious(text):s.search.findNext(text);$('#terminal-find-state').textContent=text?(match?'已定位':'无匹配'):'';}
  function rename(s){const pane=s.pane.querySelector('.terminal-pane-label');pane.innerHTML=`<form class="terminal-rename"><input aria-label="会话名称" maxlength="50" value="${esc(s.name)}"><button>保存</button></form>`;const form=pane.querySelector('form'),input=form.querySelector('input');input.focus();input.select();form.onsubmit=async e=>{e.preventDefault();const name=input.value.trim();if(!name)return;try{if(s.mode==='host')await api('/api/terminals/'+s.id,'PATCH',{name});s.name=name;pane.innerHTML=`<span>${esc(name)}</span><small>${s.mode==='host'?'本机 · 非隔离':'沙箱'}</small>`;update();}catch(error){notice(error.message);}};}
  function more(trigger,s=current()){if(!s)return;window.DongranUI.showMenu(trigger,{label:'终端操作',items:[{value:'copy',label:'复制选中内容',icon:'copy'},{value:'paste',label:'粘贴',icon:'clipboard'},{value:'all',label:'全选',icon:'text-select'},{value:'clear',label:'清空屏幕',icon:'eraser'},{value:'rename',label:'重命名会话',icon:'pencil'},{value:'export',label:'保存输出',icon:'download'},{value:'restart',label:'重新启动会话',icon:'rotate-cw'},{type:'separator'},{value:'close',label:'终止并关闭会话',icon:'trash-2'}],onSelect:async value=>{if(value==='copy')copy(s);if(value==='paste')paste(s);if(value==='all')s.term.selectAll();if(value==='clear')s.term.clear();if(value==='rename')rename(s);if(value==='close')closeSession(s.id);if(value==='restart'){if(!project||project.id!==s.projectId){notice('请先切换回该终端所属项目。');return;}const kind=s.mode,profile=s.profile;await closeSession(s.id);await create(kind,profile);}if(value==='export'){let lines=[];const buffer=s.term.buffer.active;for(let i=0;i<buffer.length;i++)lines.push(buffer.getLine(i)?.translateToString(true)||'');const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='terminal-output.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}});}
  function setOpen(open){dock.hidden=!open;dock.closest('.workspace').classList.toggle('terminal-maximized',open&&dock.classList.contains('is-expanded'));toggle.classList.toggle('active',open);toggle.setAttribute('aria-expanded',String(open));if(open){void restore();fitAll();if(current()?.mode==='host')current().term.focus();else if(current())$('#terminal-input').focus();}else toggle.focus();}
  toggle.onclick=()=>setOpen(dock.hidden);$('#terminal-close').onclick=()=>setOpen(false);
  $('#terminal-empty-host').onclick=()=>create('host');$('#terminal-empty-sandbox').onclick=()=>create('sandbox');$('#terminal-new').onclick=()=>create(mode);
  $('#terminal-mode').onclick=e=>window.DongranUI.showMenu(e.currentTarget,{label:'新建会话模式',showDescriptions:true,items:[{value:'host',label:'本机交互终端',description:'真实项目目录 · 可联网 · 非隔离',icon:'monitor',checked:mode==='host'},{value:'sandbox',label:'沙箱命令',description:'项目快照 · 禁止联网 · 逐条执行',icon:'shield',checked:mode==='sandbox'}],onSelect:value=>create(value)});
  $('#terminal-profiles').onclick=async e=>{const trigger=e.currentTarget;try{await loadProfiles();window.DongranUI.showMenu(trigger,{label:'新建本机 Shell',items:profiles.map(p=>({value:p.id,label:p.label,icon:'terminal'})),onSelect:id=>create('host',id)});}catch(error){notice(error.message);}};
  $('#terminal-split').onclick=()=>{if(split){split=null;update();}else{const s=current();create(s?.mode||mode,s?.profile,true);}};
  $('#terminal-search').onclick=find;$('#terminal-more').onclick=e=>more(e.currentTarget);$('#terminal-stop').onclick=()=>closeSession(active);
  $('#terminal-expand').onclick=()=>{const expanded=dock.classList.toggle('is-expanded');dock.closest('.workspace').classList.toggle('terminal-maximized',expanded);$('#terminal-expand').setAttribute('aria-pressed',expanded);$('#terminal-expand').innerHTML=icon(expanded?'minimize-2':'maximize-2');icons();fitAll();};
  $('#terminal-sandbox').onclick=()=>window.DongranSettings?.open('permissions');
  $('#terminal-form').onsubmit=e=>{e.preventDefault();const command=$('#terminal-input').value.trim();if(command){$('#terminal-input').value='';sandboxCommand(command);}};
  $('#terminal-input').onkeydown=e=>{const s=current();if(!s||e.isComposing)return;if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();s.historyIndex=Math.max(0,Math.min(s.history.length,s.historyIndex+(e.key==='ArrowUp'?-1:1)));e.target.value=s.history[s.historyIndex]||'';}};
  $('#terminal-cancel-command').onclick=()=>{const id=current()?.running;if(id&&id!=='starting')api('/api/commands/'+id+'/cancel','POST').catch(e=>notice(e.message));};
  $('#terminal-find').onsubmit=e=>{e.preventDefault();search();};$('#terminal-find-input').oninput=()=>search();$('[data-find="previous"]').onclick=()=>search(true);$('[data-find="close"]').onclick=()=>{$('#terminal-find').hidden=true;current()?.term.focus();};$('#terminal-find-input').onkeydown=e=>{if(e.key==='Escape'){$('#terminal-find').hidden=true;current()?.term.focus();}};
  const resizer=$('.terminal-resizer');resizer.onpointerdown=e=>{e.preventDefault();dock.classList.remove('is-expanded');dock.closest('.workspace').classList.remove('terminal-maximized');$('#terminal-expand').setAttribute('aria-pressed','false');$('#terminal-expand').innerHTML=icon('maximize-2');icons();resizer.setPointerCapture(e.pointerId);const start=e.clientY,height=dock.getBoundingClientRect().height;const move=event=>{dock.style.setProperty('--terminal-height',Math.max(160,Math.min(window.innerHeight*.8,height+start-event.clientY))+'px');fitAll();};resizer.onpointermove=move;resizer.onpointerup=()=>{resizer.onpointermove=null;resizer.releasePointerCapture(e.pointerId);};};resizer.onkeydown=e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();dock.style.setProperty('--terminal-height',Math.max(160,Math.min(window.innerHeight*.8,dock.clientHeight+(e.key==='ArrowUp'?20:-20)))+'px');fitAll();}};
  const divider=$('#terminal-divider');divider.onpointerdown=e=>{e.preventDefault();divider.setPointerCapture(e.pointerId);divider.onpointermove=event=>{const rect=$('#terminal-panes').getBoundingClientRect();splitRatio=Math.max(20,Math.min(80,(event.clientX-rect.left)/rect.width*100));applySplit();fitAll();};divider.onpointerup=()=>{divider.onpointermove=null;divider.releasePointerCapture(e.pointerId);};};divider.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();splitRatio=Math.max(20,Math.min(80,splitRatio+(e.key==='ArrowLeft'?-5:5)));applySplit();fitAll();}};
  window.addEventListener('projectchange',e=>{project=e.detail?.id?e.detail:null;update();});
  window.addEventListener('backendready',()=>{void restore();});window.addEventListener('sandboxchange',update);
  window.addEventListener('settingschange',e=>{const prefs=e.detail.settings;dock.style.setProperty('--terminal-height',(prefs.terminalHeight||300)+'px');for(const s of sessions.values()){s.term.options.fontSize=prefs.terminalFontSize||13;s.term.options.theme=theme();}fitAll();});
  new MutationObserver(()=>{for(const s of sessions.values())s.term.options.theme=theme();}).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});
  window.DongranTerminal={open:()=>setOpen(true),focus:()=>{setOpen(true);current()?.term.focus();}};
  update();
})();
