const { chromium } = require('playwright');
const { spawn, execFileSync } = require('node:child_process');
const http = require('node:http');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');

// Deterministic model fixture. The service, SQLite, filesystem and command runner are real.
(async () => {
  const root=path.resolve(__dirname,'..');
  const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'dongran-e2e-'));
  const data=path.join(temporary,'data'),project=path.join(temporary,'project');
  fs.mkdirSync(project);fs.writeFileSync(path.join(project,'README.md'),'integration project\n');
  const git=(...args)=>execFileSync('git',['-c','safe.directory='+project,'-C',project,...args],{encoding:'utf8',windowsHide:true});
  git('init','-b','main');git('config','core.autocrlf','false');git('config','user.name','UI Integration');git('config','user.email','ui@example.invalid');
  git('add','README.md');git('commit','-m','Initial project');
  const modelRequests=[];
  const model=http.createServer(async(req,res)=>{
    let raw='';for await(const chunk of req)raw+=chunk;
    const input=JSON.parse(raw);
    modelRequests.push({model:input.model,key:req.headers.authorization,url:req.url});
    const has=id=>input.messages.some(message=>message.tool_call_id===id);
    let delta;
    if(input.messages.filter(m=>m.role==='user').at(-1)?.content.startsWith('引用验证')){
      if(!has('fixture-knowledge'))delta={tool_calls:[{index:0,id:'fixture-knowledge',type:'function',function:{name:'search_knowledge',arguments:JSON.stringify({query:'可追溯验收词'})}}]};
      else {const row=JSON.parse(input.messages.find(m=>m.tool_call_id==='fixture-knowledge').content)[0];delta={content:'找到资料：[引用来源](knowledge://'+row.id+'/'+row.chunkId+')'};}
    }
    else if(input.messages.filter(m=>m.role==='user').at(-1)?.content.startsWith('补充'))delta={content:'已收到补充要求，继续对话验证通过。'+('\n长回答验收行。'.repeat(80))};
    else if(!input.tools?.length)delta={content:'OK · 模型连接测试'};
    else if(!has('fixture-write'))delta={tool_calls:[{index:0,id:'fixture-write',type:'function',function:{name:'write_file',arguments:JSON.stringify({path:'requirements.md',content:'# 需求\n\n验收：完成真实文件写入和运行验证。'})}}]};
    else if(!has('fixture-command'))delta={tool_calls:[{index:0,id:'fixture-command',type:'function',function:{name:'run_command',arguments:JSON.stringify({command:'echo dongran-agent-verified',timeout:30})}}]};
    else delta={content:'已生成 requirements.md，运行验证输出 dongran-agent-verified。'+('\n长历史对话验收行。'.repeat(80))};
    if(input.messages.filter(m=>m.role==='user').at(-1)?.content.startsWith('补充'))await new Promise(r=>setTimeout(r,2500));
    res.writeHead(200,{'Content-Type':'text/event-stream'});
    res.end('data: '+JSON.stringify({choices:[{delta,finish_reason:delta.tool_calls?'tool_calls':'stop'}]})+'\n\ndata: [DONE]\n\n');
  });
  await new Promise(resolve=>model.listen(0,'127.0.0.1',resolve));
  let backend,browser,page,base;
  const errors=[];
  const java=process.env.JAVA_HOME?path.join(process.env.JAVA_HOME,'bin',process.platform==='win32'?'java.exe':'java'):(process.platform==='win32'?'D:\\RunEnvironment\\Java\\jdk21\\bin\\java.exe':'java');
  async function startBackend(){
    backend=spawn(java,['-jar',path.join(root,'backend/target/dongran-backend-0.1.0-SNAPSHOT.jar'),'--server.port=0','--dongran.data-dir='+data],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe']});
    let logs='';backend.stdout.on('data',chunk=>logs+=chunk);backend.stderr.on('data',chunk=>logs+=chunk);
    const deadline=Date.now()+30000;
    while(Date.now()<deadline){
      if(backend.exitCode!==null)throw new Error('Backend failed: '+logs);
      try{const runtime=JSON.parse(fs.readFileSync(path.join(data,'runtime.json'),'utf8'));if(runtime.pid===backend.pid){base='http://127.0.0.1:'+runtime.port;return;}}catch{}
      await new Promise(resolve=>setTimeout(resolve,200));
    }
    throw new Error('Backend timeout: '+logs);
  }
  async function stopBackend(){
    if(!backend||backend.exitCode!==null)return;
    await new Promise(resolve=>{backend.once('exit',resolve);backend.kill();});
  }
  const call=(endpoint,method='GET',body)=>page.evaluate(async({endpoint,method,body})=>DongranRuntime.request(endpoint,method,body),{endpoint,method,body});
  try{
    await startBackend();
    browser=await chromium.launch({...(process.platform==='win32'?{executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'}:{}),headless:true});
    page=await browser.newPage({viewport:{width:1440,height:1000}});
    page.on('pageerror',error=>errors.push(error.stack||error.message));
    await page.goto(base);
    await page.waitForFunction(()=>document.querySelector('#runtime-recent')&&DongranBackend.isAvailable());
    const sandboxStatus=await call('/api/sandbox/status');
    assert.equal(sandboxStatus.available,true,JSON.stringify(sandboxStatus));
    assert.equal(sandboxStatus.networkIsolation,true);
    assert.equal(sandboxStatus.policy.mode,'required');
    await page.evaluate(()=>DongranSettings.open('permissions'));
    await page.waitForFunction(()=>document.querySelector('[data-sandbox-card]')?.dataset.state==='available');
    await page.screenshot({path:path.join(root,'.runtime','sandbox-live-settings.png'),animations:'disabled'});
    await page.evaluate(()=>DongranSettings.close());
    await page.evaluate(()=>DongranSettings.open('account'));
    await page.locator('#account-nickname').fill('真实账户测试');
    await page.locator('#account-nickname').dispatchEvent('change');
    await page.waitForFunction(()=>document.querySelector('#settings-status').textContent.includes('本机数据库'));
    assert.equal((await call('/api/account')).accountNickname,'真实账户测试');
    await page.evaluate(()=>DongranSettings.close());
    await page.evaluate(project=>DongranRuntime.open(project),project);
    await page.evaluate(()=>DongranSettings.open('models'));
    await page.locator('#provider-add').click();
    await page.locator('#provider-name').fill('测试模型');
    await page.locator('#provider-url').fill('http://127.0.0.1:'+model.address().port+'/v1');
    await page.locator('#provider-model').fill('fixture');
    await page.locator('#provider-key').fill('fixture-first-key');
    await page.locator('#provider-remember').uncheck();
    await page.locator('#provider-save').click();
    await page.waitForFunction(()=>!document.querySelector('#provider-editor').open);
    await page.evaluate(()=>DongranSettings.set('confirmPlan',false));
    await page.locator('[data-provider-action="test"]').click();
    await page.waitForFunction(()=>document.querySelector('.provider-test-state')?.textContent.includes('连接成功'));
    assert.equal(modelRequests.at(-1).model,'fixture');
    assert.equal(modelRequests.at(-1).key,'Bearer fixture-first-key');
    const firstProvider=(await call('/api/model-providers'))[0];
    await page.locator('#provider-add').click();
    await page.locator('[data-provider-kind="local"]').click();
    await page.locator('#provider-name').fill('本地推理环境');
    await page.locator('#provider-url').fill('http://127.0.0.1:'+model.address().port+'/alternate/v1');
    await page.locator('#provider-model').fill('fixture-second');
    await page.locator('#provider-key').fill('fixture-second-key');
    await page.locator('#provider-remember').uncheck();
    await page.screenshot({path:path.join(root,'.runtime','provider-editor.png'),animations:'disabled'});
    await page.locator('#provider-save').click();
    await page.waitForFunction(()=>!document.querySelector('#provider-editor').open);
    await page.waitForFunction(()=>document.querySelectorAll('.provider-card').length===2);
    const secondProvider=(await call('/api/model-providers')).find(p=>p.id!==firstProvider.id);
    const second=page.locator('[data-provider-id="'+secondProvider.id+'"]');
    await second.locator('[data-provider-action="test"]').click();
    await page.waitForFunction(id=>document.querySelector('[data-provider-id="'+id+'"] .provider-test-state')?.textContent.includes('连接成功'),secondProvider.id);
    assert.equal(modelRequests.at(-1).model,'fixture-second');
    assert.equal(modelRequests.at(-1).key,'Bearer fixture-second-key');
    assert.equal(modelRequests.at(-1).url,'/alternate/v1/chat/completions');
    assert.equal((await call('/api/models/status')).providerId,firstProvider.id,'Testing an inactive provider must not activate it');
    await second.locator('[data-provider-action="activate"]').click();
    await page.waitForFunction(()=>document.querySelector('#model-label').textContent==='本地推理环境');
    await page.screenshot({path:path.join(root,'.runtime','model-providers.png'),animations:'disabled'});
    await second.locator('[data-provider-action="more"]').click();
    await page.locator('.menu-option[data-value="duplicate"]').click();
    await page.waitForSelector('#provider-editor[open]');
    assert.equal(await page.locator('#provider-key').inputValue(),'');
    const copied=(await call('/api/model-providers')).find(p=>p.name.endsWith('副本'));
    assert.equal(copied.credentialConfigured,false);
    await page.locator('#provider-name').fill('备用配置');
    await page.locator('#provider-save').click();
    await page.waitForFunction(()=>!document.querySelector('#provider-editor').open);
    const copyCard=page.locator('[data-provider-id="'+copied.id+'"]');
    await copyCard.locator('[data-provider-action="more"]').click();
    await page.locator('.menu-option[data-value="delete"]').click();
    await page.locator('#provider-delete-confirm').click();
    await page.waitForFunction(()=>!document.querySelector('#dialog').open);
    await page.waitForFunction(()=>document.querySelectorAll('.provider-card').length===2);
    await page.evaluate(()=>DongranSettings.set('theme','dark'));
    await page.screenshot({path:path.join(root,'.runtime','model-providers-dark.png'),animations:'disabled'});
    await page.setViewportSize({width:1024,height:768});
    await page.locator('#provider-add').click();
    assert.equal(await page.locator('#provider-save').isVisible(),true);
    const editorBounds=await page.locator('#provider-editor').boundingBox();
    assert.ok(editorBounds.x>=0&&editorBounds.y>=0&&editorBounds.y+editorBounds.height<=769);
    await page.screenshot({path:path.join(root,'.runtime','provider-editor-small.png'),animations:'disabled'});
    await page.locator('#provider-editor-cancel').click();
    await page.waitForFunction(()=>!document.querySelector('#provider-editor').open);
    await page.setViewportSize({width:1440,height:1000});
    await page.evaluate(()=>DongranSettings.set('theme','light'));
    await page.evaluate(()=>DongranSettings.close());
    await page.locator('#model-trigger').click();
    await page.locator('.menu-option[data-value="'+firstProvider.id+'"]').click();
    await page.waitForFunction(()=>document.querySelector('#model-label').textContent==='测试模型');
    // Real Git actions from the bottom-right entry, operating only on a disposable fixture.
    fs.writeFileSync(path.join(project,'README.md'),'integration project\nnew requirement\n');
    fs.writeFileSync(path.join(project,'design.md'),'# Design\n\nAgent workspace\n');
    await page.locator('#git-status-button').click();
    await page.waitForSelector('#git-workspace .git-file-row');
    await page.locator('[data-git-file="README.md"]').click();
    await page.waitForFunction(()=>document.querySelector('.git-diff-code')?.textContent.includes('+new requirement'));
    await page.screenshot({path:path.join(root,'.runtime','git-workspace.png'),animations:'disabled'});
    await page.locator('.git-file-row').filter({has:page.locator('[data-git-file="README.md"]')}).locator('input').check();
    await page.locator('[data-git-action="stage"]').click();
    await page.waitForSelector('[data-git-file="README.md"][data-staged="true"]');
    fs.writeFileSync(path.join(project,'README.md'),'integration project\nnew requirement\nkeep unstaged\n');
    await page.locator('[data-git-action="refresh"]').click();
    await page.waitForSelector('[data-git-file="README.md"][data-staged="false"]');
    await page.locator('[data-git-file="README.md"][data-staged="true"]').click();
    await page.waitForFunction(()=>document.querySelector('#git-diff-title')?.textContent.includes('已暂存'));
    await page.locator('#git-commit-message').fill('Add requirement');
    await page.locator('[data-git-action="commit"]').click();
    await page.locator('#git-confirm-submit').click();
    await page.waitForFunction(()=>!document.querySelector('.git-confirm-layer')&&document.querySelector('.git-notice')?.textContent.includes('Add requirement'));
    assert.equal(git('show','HEAD:README.md'),'integration project\nnew requirement\n');
    assert.match(fs.readFileSync(path.join(project,'README.md'),'utf8'),/keep unstaged/);
    await page.locator('[data-git-file="README.md"][data-staged="false"]').click();
    await page.waitForFunction(()=>!document.querySelector('[data-git-action="discard"]').disabled);
    await page.locator('[data-git-action="discard"]').click();await page.locator('#git-confirm-submit').click();
    await page.waitForFunction(()=>!document.querySelector('[data-git-file="README.md"]'));
    assert.equal(fs.readFileSync(path.join(project,'README.md'),'utf8'),'integration project\nnew requirement\n');
    await page.locator('.git-file-row input').check();await page.locator('[data-git-action="stage"]').click();
    await page.waitForSelector('[data-git-file="design.md"][data-staged="true"]');
    await page.locator('.git-file-row input').check();await page.locator('[data-git-action="unstage"]').click();
    await page.waitForSelector('[data-git-file="design.md"][data-staged="false"]');
    await page.locator('.git-file-row input').check();await page.locator('[data-git-action="stage"]').click();
    await page.waitForSelector('[data-git-file="design.md"][data-staged="true"]');
    await page.locator('#git-commit-message').fill('Add design');
    await page.locator('[data-git-action="commit"]').click();await page.locator('#git-confirm-submit').click();
    await page.waitForFunction(()=>!document.querySelector('.git-file-row'));
    await page.locator('[data-git-tab="branches"]').click();
    await page.locator('[data-git-action="create-branch"]').click();
    await page.locator('#git-new-branch').fill('feature/ui');
    await page.locator('#git-confirm-submit').click();
    await page.waitForFunction(()=>document.querySelector('#branch-name').textContent==='feature/ui');
    await page.locator('[data-git-checkout="main"]').click();await page.locator('#git-confirm-submit').click();
    await page.waitForFunction(()=>document.querySelector('#branch-name').textContent==='main');
    await page.locator('[data-git-tab="history"]').click();
    assert.equal(await page.locator('.git-log-row').count(),3);
    await page.locator('.git-log-row').first().click();
    assert.match(await page.locator('#git-log-detail').innerText(),/Add design/);
    await page.screenshot({path:path.join(root,'.runtime','git-history.png'),animations:'disabled'});
    await page.evaluate(()=>DongranSettings.set('theme','dark'));
    await page.setViewportSize({width:1024,height:768});
    await page.screenshot({path:path.join(root,'.runtime','git-history-dark-small.png'),animations:'disabled'});
    const gitBounds=await page.locator('#git-workspace').boundingBox();
    assert.ok(gitBounds.x>=0&&gitBounds.y>=0&&gitBounds.x+gitBounds.width<=1025);
    await page.locator('[data-git-action="close"]').click();
    await page.waitForFunction(()=>!document.querySelector('#git-workspace').open);
    await page.setViewportSize({width:1440,height:1000});
    await page.evaluate(()=>DongranSettings.set('theme','light'));
    await page.locator('#prompt').fill('生成需求文档');
    await page.locator('#prompt').press('Shift+Enter');
    await page.locator('#prompt').press('End');await page.locator('#prompt').type('并运行验证');
    assert.match(await page.locator('#prompt').inputValue(),/\n/);
    await page.locator('#prompt').dispatchEvent('keydown',{key:'Enter',isComposing:true,keyCode:229});
    assert.equal(await page.locator('.task-heading').count(),0);
    await page.locator('#prompt').press('Enter');
    await page.waitForSelector('.permission [data-allowed="true"]');
    assert.equal(fs.existsSync(path.join(project,'requirements.md')),false);
    await page.locator('.permission [data-allowed="true"]').click();
    await page.waitForFunction(()=>document.querySelector('.permission')?.textContent.includes('run_command'));
    assert.match(fs.readFileSync(path.join(project,'requirements.md'),'utf8'),/验收/);
    await page.locator('.permission [data-allowed="true"]').click();
    await page.waitForFunction(()=>document.querySelector('.task-heading .badge')?.textContent==='已完成',{},{timeout:20000});
    const taskId=await page.evaluate(()=>state.active);
    assert.match(await page.locator('#messages').innerText(),/dongran-agent-verified/);
    assert.equal(modelRequests.at(-1).model,'fixture');
    assert.equal(modelRequests.at(-1).key,'Bearer fixture-first-key');
    await page.screenshot({path:path.join(root,'.runtime','backend-task.png'),animations:'disabled'});
    await page.locator('#messages').evaluate(el=>el.scrollTop=0);
    await page.waitForFunction(()=>!document.querySelector('#chat-latest').hidden);
    await page.locator('#chat-latest').click();
    assert.ok(await page.locator('#messages').evaluate(el=>el.scrollHeight-el.clientHeight-el.scrollTop<80));
    await page.locator('#messages').evaluate(el=>el.scrollTop=0);
    await page.waitForFunction(()=>!document.querySelector('#chat-latest').hidden);
    await page.evaluate(()=>DongranSettings.set('confirmPlan',true));
    await page.locator('#prompt').fill('补充：列出验收标准');
    await page.locator('#prompt').press('Enter');
    await page.waitForFunction(()=>document.querySelector('.task-heading .badge')?.textContent==='执行中');
    assert.ok(await page.locator('#messages').evaluate(el=>el.scrollHeight-el.clientHeight-el.scrollTop<80),'Sending follows newest answer');
    const initialElapsed=await page.locator('#task-elapsed').innerText();
    await page.locator('#messages').evaluate(el=>el.scrollTop=0);
    await page.waitForFunction(()=>!document.querySelector('#chat-latest').hidden);
    await page.locator('#prompt').fill('保留下一轮草稿');await page.locator('#prompt').press('Enter');
    assert.equal(await page.locator('#prompt').inputValue(),'保留下一轮草稿');
    await page.waitForFunction(previous=>document.querySelector('#task-elapsed')?.textContent!==previous,initialElapsed);
    await page.locator('#prompt').fill('');
    await page.waitForFunction(()=>document.querySelector('#messages').textContent.includes('继续对话验证通过'));
    await page.waitForFunction(()=>document.querySelector('.task-heading .badge')?.textContent==='已完成');

    assert.ok(await page.locator('#messages').evaluate(el=>el.scrollTop<40),'New response preserves user history position');
    await page.locator('#chat-latest').click();
    const frozenElapsed=await page.locator('#task-elapsed').innerText();await page.waitForTimeout(1200);assert.equal(await page.locator('#task-elapsed').innerText(),frozenElapsed);
    assert.equal(await page.locator('.permission').count(),0,'A completed answer must not ask for plan confirmation');
    await page.screenshot({path:path.join(root,'.runtime','answer-without-approval.png'),animations:'disabled'});

    await call('/api/knowledge','POST',{name:'引用验收资料',content:'前言\n可追溯验收词：确认片段定位高亮。'});
    await page.locator('#prompt').fill('引用验证：查找知识库');await page.locator('#prompt').press('Enter');
    await page.waitForFunction(()=>document.querySelector('.runtime-message .knowledge-citation'));
    await page.locator('.knowledge-sources .knowledge-citation').first().click();
    await page.waitForFunction(()=>document.querySelector('.knowledge-frame')?.contentDocument?.querySelector('#knowledge-hit .keyword-hit'));
    assert.match(await page.locator('.knowledge-frame').evaluate(frame=>frame.contentDocument.querySelector('#knowledge-hit').textContent),/可追溯验收词/);
    await page.locator('#knowledge-preview [data-preview="close"]').click();await page.waitForFunction(()=>!document.querySelector('#knowledge-preview').open);
    await page.locator('#terminal-toggle').click();
    await page.locator('#terminal-input').fill('echo terminal-real-output');
    await page.locator('#terminal-input').press('Enter');
    await page.waitForFunction(()=>document.querySelector('#terminal-output').textContent.includes('completed · exit 0'));
    assert.match(await page.locator('#terminal-output').innerText(),/terminal-real-output/);
    await page.locator('#terminal-close').click();

    await page.locator('[data-action="knowledge"]').first().click();
    await page.locator('#runtime-knowledge-add').click();
    await page.locator('#runtime-knowledge-name').fill('产品需求资料');
    await page.locator('#runtime-knowledge-content').fill('这里包含产品需求验收标准与边界。');
    await page.locator('#runtime-knowledge-form .primary').click();
    await page.waitForFunction(()=>!document.querySelector('#dialog').open);
    await page.waitForSelector('[data-knowledge-id]');
    await page.locator('#runtime-knowledge-query').fill('验收标准');
    await page.waitForFunction(()=>document.querySelector('#runtime-knowledge-list').textContent.includes('产品需求资料'));

    await page.locator('[data-action="schedules"]').first().click();
    await page.locator('#schedule-add').click();
    await page.locator('#schedule-name').fill('每日需求核对');
    await page.locator('#schedule-prompt').fill('分析需求中的遗漏');
    await page.locator('#schedule-enabled').click();
    await page.locator('#schedule-save').click();
    await page.waitForFunction(()=>!document.querySelector('#dialog').open);
    const snapshot=await call('/api/schedules');
    assert.equal(snapshot.tasks[0].name,'每日需求核对');
    assert.equal(snapshot.tasks[0].enabled,false);
    await page.screenshot({path:path.join(root,'.runtime','backend-schedules.png'),animations:'disabled'});
    // A full process restart checks SQLite persistence, not just browser state.
    await page.close();await stopBackend();await startBackend();
    page=await browser.newPage({viewport:{width:1440,height:1000}});
    page.on('pageerror',error=>errors.push(error.stack||error.message));
    await page.goto(base);await page.waitForFunction(()=>DongranBackend.isAvailable());
    assert.equal((await call('/api/account')).accountNickname,'真实账户测试');
    assert.equal((await call('/api/tasks/'+taskId)).status,'completed');
    assert.equal((await call('/api/schedules')).tasks[0].name,'每日需求核对');
    const restoredProviders=await call('/api/model-providers');
    assert.equal(restoredProviders.length,2);
    assert.equal(restoredProviders.find(p=>p.active).id,firstProvider.id);
    assert.equal(restoredProviders.every(p=>!p.credentialConfigured),true,'Session-only secrets must not survive a restart');
    await page.evaluate(project=>DongranRuntime.open(project),project);
    await page.locator('[data-action="knowledge"]').first().click();
    await page.waitForSelector('[data-knowledge-id]');
    assert.match(await page.locator('#runtime-knowledge-list').innerText(),/产品需求资料/);
    assert.deepEqual(errors,[]);
    console.log('PASS: provider CRUD, separate keys and routing, inactive tests, quick switching, Git diff/stage/unstage/commit/discard/branches/history, light/dark desktop views, SSE task, approvals, real file/command, terminal, knowledge, schedule and restart persistence.');
  }catch(error){
    console.error('Browser errors:',errors);
    if(page){await page.screenshot({path:path.join(root,'.runtime','backend-failure.png')}).catch(()=>{});console.error('UI:',await page.locator('body').innerText().catch(()=>''));}
    throw error;
  }finally{
    await browser?.close();await stopBackend();await new Promise(resolve=>model.close(resolve));
    console.log('Test data:',temporary);
  }
})().catch(error=>{console.error(error);process.exitCode=1;});
